name: build
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
jobs:
  build:
    runs-on: self-hosted
    steps: 
    - name: Clone repository 
      uses: actions/checkout@v4
    - name: Build image
      run: docker build . --tag=$GITHUB_JOB
    - name: Remove image
      run: docker image rm -f $GITHUB_JOB