name: deployment

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - run: echo "It work"
    - run: ls
    - name: docker compose
      run: docker compose up
