name: deployment
on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]
jobs:
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
    - name: Clone repository 
      uses: actions/checkout@v4
    - name: Copy env
      run: cp .env.example .env
    - name: deploy
      run: docker compose -f ci.docker-compose.yml up --build --detach --force-recreate
